/* Optional integration checks. Run with Playwright resolvable and CHROME_PATH set if needed. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {pathToFileURL}=require('node:url'),{chromium}=require('playwright');
(async()=>{
  const root=path.resolve(__dirname,'..'),out=process.env.DEMO_SCREENSHOTS||path.join(os.tmpdir(),'cs464-expansion-screenshots');fs.mkdirSync(out,{recursive:true});
  const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
  const context=await browser.newContext({viewport:{width:1440,height:1050},offline:true});const page=await context.newPage(),errors=[];
  page.on('pageerror',e=>errors.push(e.message));page.on('console',e=>{if(e.type()==='error')errors.push(e.text());});
  const folders=fs.readdirSync(root).filter(n=>/^\d/.test(n)&&parseInt(n)>=6);
  const open=async n=>{await page.goto(pathToFileURL(path.join(root,folders.find(s=>parseInt(s)===n),'index.html')).href);await page.waitForFunction(()=>window.demoState);};
  const flush=()=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));
  const value=async(id,v)=>{await page.locator('#'+id).evaluate((el,v)=>{el.value=v;el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));},String(v));await flush();};
  const click=async id=>{await page.click('#'+id);await flush();};
  const check=async(id,checked)=>{await page.locator('#'+id).setChecked(checked);await flush();};
  const state=()=>page.evaluate(()=>demoState),near=(a,b,e=1e-5)=>assert.ok(Math.abs(a-b)<e,`${a} vs ${b}`);
  try {
    await open(6);await check('motion',false);await value('ahead',0);await value('mode','rigid');await value('position',5);near((await state()).error,0);await value('mode','smooth');await value('response',1);await value('position',-5);assert.ok(Math.abs((await state()).error)>1);await value('mode','dead');await value('zone',1);await flush();assert.ok(Math.abs((await state()).error)<=1.001);await value('mode','spring');assert.ok(Number.isFinite((await state()).follower));
    await open(7);for(const mode of ['seek','flee','arrive','pursue','evade']){await value('mode',mode);const s=await state();assert.equal(s.mode,mode);assert.ok(s.speed<=4.001);assert.ok(s.force<=5.001);}await check('moving',true);await check('avoid',false);await value('tx',-4);await check('moving',false);
    await open(8);await click('launch');await page.waitForFunction(()=>demoState.hits===1);near((await state()).outgoing,7);await value('mode','slide');await click('launch');await page.waitForFunction(()=>demoState.hits===1);near((await state()).outgoing,3.5);near((await state()).velocity[2],0);
    await open(9);near((await state()).eulerYaw,0);near((await state()).quaternionTurn,10);near((await state()).shortestPath,20);await value('method','nlerp');near((await state()).quaternionTurn,10);await click('lock');near((await state()).alignment,1);await value('pitch',0);near((await state()).alignment,0);
    await open(10);await click('critical');near((await state()).ratio,1,.005);await click('reset');await click('impulse');assert.ok((await state()).states[0].v>0);for(const mode of ['recoil','scale','carriage'])await value('mode',mode);
    await open(11);await click('launch');await page.waitForFunction(()=>demoState.hits[0]===true);assert.equal((await state()).hits[1],false);await click('reset');await value('speed',5);await value('gravity',20);assert.equal((await state()).solution,null);await click('launch');assert.ok((await state()).status.includes('NO INTERCEPTION'));await value('mode','ballistic');await value('speed',16);await click('launch');await page.waitForFunction(()=>demoState.time>.1);
    await open(12);const before=(await state()).world;await check('lock',true);await value('px',-3);await value('yaw',100);await value('scale',2);const after=await state();after.world.forEach((v,i)=>near(v,before[i]));assert.ok(after.error<1e-8);await check('lock',false);assert.ok(Math.abs((await state()).world[0]-before[0])>1);
    await open(13);for(const fps of [15,144]){await value('fps',fps);await click('trial');await page.waitForFunction(()=>demoState.complete);const s=await state();near(s.distances[1],8);near(s.distances[2],8);near(s.distances[0],4/60*fps*2);}await check('hitch',true);await click('trial');await page.waitForFunction(()=>demoState.complete);near((await state()).distances[1],8);near((await state()).distances[2],8);
    await open(14);await click('combo');await page.waitForFunction(()=>demoState.attacks===2);assert.ok((await state()).hits>=1);await value('buffer',0);await click('combo');await page.waitForFunction(()=>demoState.attacks===1&&demoState.phase==='ready');assert.equal((await state()).attacks,1);await value('distance',7);await click('reset');await click('attack');await page.waitForFunction(()=>demoState.phase==='ready');assert.equal((await state()).hits,0);
    await open(15);await value('scrub',0);let s=await state();near(s.positions[0][0],s.points[0][0]);await value('scrub',100);s=await state();near(s.positions[1][0],s.points[3][0]);await value('point',1);await value('cx',-7);await value('cy',6);s=await state();assert.deepEqual(s.points[1],[-7,6]);
    const screen=await page.evaluate(()=>{const c=document.querySelector('#stage canvas'),r=c.getBoundingClientRect(),camera=new THREE.PerspectiveCamera(43,r.width/r.height,.1,200);camera.position.set(0,1,25);camera.lookAt(0,1,0);camera.updateMatrixWorld();const v=new THREE.Vector3(...demoState.points[1],0).project(camera);return{x:r.x+(v.x+1)/2*r.width,y:r.y+(1-v.y)/2*r.height};});await page.mouse.move(screen.x,screen.y);await page.mouse.down();await page.mouse.move(screen.x+50,screen.y+30,{steps:6});await page.mouse.up();await flush();assert.ok((await state()).points[1][0]>-6.8);
    await open(16);assert.ok((await state()).error<1e-5);await value('tx',6);assert.equal((await state()).reachable,false);await value('mode','terrain');await value('tx',2);await value('upper',1);await value('lower',2);await value('hip',6);const err=(await state()).error;await check('adjust',true);assert.ok((await state()).error<err);await check('reverse',true);s=await state();near(Math.hypot(s.knee[0]-s.root[0],s.knee[1]-s.root[1]),1);near(Math.hypot(s.foot[0]-s.knee[0],s.foot[1]-s.knee[1]),2);
    await open(17);assert.equal((await state()).audioState,'not-started');await value('delay',200);await click('compare');await page.waitForFunction(()=>demoState.count===2);s=await state();assert.equal(s.audioState,'running');const designed=s.events.find(e=>e.designed);near(designed.sound-designed.start,.2);await click('reset');await page.waitForFunction(()=>demoState.pendingSources===0);for(const preset of ['impact','step','pickup']){await value('preset',preset);await click('designed');await page.waitForFunction(()=>demoState.pendingSources>0);await click('reset');}
    console.log('PASS: all 12 labs’ mathematical and interaction scenarios.');
    for(const width of [390,768,1440]){await page.setViewportSize({width,height:950});for(const folder of folders){await open(parseInt(folder));assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${folder} overflows at ${width}`);assert.ok(await page.evaluate(()=>{const finite=v=>typeof v==='number'?Number.isFinite(v):Array.isArray(v)?v.every(finite):v&&typeof v==='object'?Object.values(v).every(finite):true;return finite(demoState);}),folder+' non-finite state');if(width===390||width===1440)await page.screenshot({path:path.join(out,folder+'-'+width+'.png'),fullPage:true});}}
    console.log('PASS: 390, 768, and 1440 pixel layouts; screenshots saved.');
    for(const folder of folders){const isolated=fs.mkdtempSync(path.join(os.tmpdir(),'cs464-lab-'));fs.cpSync(path.join(root,folder),isolated,{recursive:true});await page.goto(pathToFileURL(path.join(isolated,'index.html')).href);await page.waitForFunction(()=>window.demoState);}
    await page.goto(pathToFileURL(path.join(root,'index.html')).href);assert.equal(await page.locator('.demo-card').count(),17);await page.fill('#catalog-search','interception');assert.equal(await page.locator('.demo-card:visible').count(),1);await page.fill('#catalog-search','');await page.click('[data-filter=maths]');assert.equal(await page.locator('.demo-card:visible').count(),7);await page.fill('#catalog-search','no-such-lab');assert.equal(await page.locator('.demo-card:visible').count(),0);
    const reduced=await browser.newContext({offline:true,reducedMotion:'reduce'}),rp=await reduced.newPage();await rp.goto(pathToFileURL(path.join(root,'06-camera-feel/index.html')).href);await rp.waitForFunction(()=>window.demoState);assert.equal(await rp.evaluate(()=>demoState.running),false);await reduced.close();
    assert.deepEqual(errors,[]);console.log('PASS: each new folder independently copied and opened offline; catalog filters; reduced-motion startup; zero browser errors.');
  } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
