"""Rebuild lab pages/assets and catalog entries for labs 06–17. Does not overwrite app.js."""
from pathlib import Path
import shutil, html, re
ROOT=Path(__file__).resolve().parents[1]
# slug, title, description, scene, metrics, formula, explanation, experiment, transfer, group
LABS=[
('06-camera-feel','Give the camera a point of view.','Compare rigid follow, smoothing, springs, dead zones, look-ahead, and speed-based zoom on the same moving subject.','Camera follow playground',['Tracking error','Subject speed','Camera FOV'],'smooth: α = 1 − exp(−λ Δt)\nspring: a = (k(target − x) − cv) / m','A camera balances framing, responsiveness, and continuity. Exponential smoothing uses elapsed time; a spring carries velocity and can overshoot. The wireframe box marks the dead zone in world space.','Pause the subject, move its X position abruptly, and compare modes. Enable look-ahead, then speed zoom. Use the response slider to change how quickly the camera catches up.','Keep look-ahead bounded. Consider camera behaviour during sudden reversals, teleports, and stops. A dead zone ignores small movements until the subject crosses its boundary.','feel'),
('07-steering-behaviours','Move with intention.','Guide an agent with seek, flee, arrive, pursue, and evade. Inspect velocity, steering force, and obstacle avoidance.','Autonomous steering field',['Target distance','Agent speed','Steering magnitude'],'desired = direction × desiredSpeed\nsteering = clamp(desired − velocity)\nvelocity += steering × Δt','Seek heads toward the current target. Pursuit predicts its future position; evade moves away from that prediction. Arrive reduces desired speed near the target. This is a steering-force model with bounded acceleration.','Click the floor to move the target. Compare seek with arrive. Enable a moving target for pursue and evade. Turn obstacle avoidance off and on to inspect the additional steering vector.','Steering is local navigation, not pathfinding. This lab uses predictive obstacle steering and circle separation; crowded or maze-like levels usually need a global route as well.','movement'),
('08-collision-maths','Meet the surface.','Fire a ball at a wall and compare reflection with sliding. Change its normal, incidence angle, restitution, and tangential friction.','Reflection & sliding bench',['Signed distance','Outgoing speed','Collision count'],'vₙ = (v · n̂)n̂; vₜ = v − vₙ\nbounce = (1 − μ)vₜ − e vₙ\nslide = (1 − μ)vₜ','A normal separates velocity into perpendicular and tangential components. Restitution e controls rebound; μ removes a fraction of tangential speed at this single contact. This is an impulse demonstration, not a full friction solver.','Set restitution to 1 and friction to 0: speed is preserved. Set restitution to 0, then compare with slide. Rotate the wall; the same calculation works in its new orientation.','Use a normalized normal. Only resolve velocity directed into the surface. A positional correction keeps the sphere from remaining inside the wall after a simulation step.','maths'),
('09-rotations','Take the shortest turn.','Compare Euler interpolation, quaternion SLERP, and normalized quaternion LERP. Inspect the aligned axes that cause gimbal lock.','Rotations & orientation',['Euler yaw','Quaternion turn','Axis alignment'],'q(t) = slerp(q₀, q₁, t)\nq and −q represent the same rotation\nYXZ lock: pitch = ±90°','Interpolating 170° to −170° as raw numbers takes a 340° route. Quaternion interpolation takes the 20° orientation path. SLERP has constant angular speed; normalized LERP usually does not.','Scrub between the default headings and compare the noses. Switch to the gimbal experiment, set pitch to 90°, and change yaw and roll: the outer and inner rotation axes align.','Quaternions avoid an Euler parameter singularity, but cannot restore a degree of freedom to a physical three-gimbal mechanism. Euler input converted to a quaternion still inherits that input ambiguity.','maths'),
('10-springs','Design the recovery.','Explore stiffness, damping, and mass. Compare your spring with critical and overdamped references, then reuse its motion for recoil or a pop-in.','Spring response bench',['Damping ratio ζ','Displacement error','Velocity'],'a = (k(target − x) − cv) / m\nc_critical = 2√(km)\nζ = c / c_critical','Below ζ = 1, a spring oscillates around its target. At critical damping it returns without oscillation; above it, recovery is slower. The reference lanes use the same stiffness and mass.','Set damping to zero, step the target, and watch persistent oscillation. Apply critical damping, then add an impulse. Switch the presentation between carriage, recoil, and scale.','Springs can drive camera lag, weapon recovery, and UI motion. This numerical simulation runs at 240 Hz; extreme parameters still require an appropriate solver and timestep.','feel'),
('11-projectile-maths','Aim where it will be.','Explore gravity-driven arcs and leading a moving target. Compare a shot at the current position with an interception solution.','Ballistics & interception',['Flight time','Launch speed','Hit / miss'],'p(t) = p₀ + v₀t + ½gt²\n|r + v_target t − ½gt²| = speed × t','The leading solver searches for the earliest reachable flight time at the selected launch speed. It includes gravity and constant target velocity. If no solution exists within 12 seconds, the lab tells you.','In interception mode, increase target velocity. Compare the teal shot at its original position with the orange leading shot. Raise gravity or reduce launch speed until the target becomes unreachable.','Prediction is only as good as its assumptions. The target moves at constant velocity during each trial; acceleration and evasive movement require new estimates. Ballistic mode instead uses the chosen launch angle.','maths'),
('12-coordinate-spaces','Know which world you are in.','Move a turret inside a translating, rotating, scaled parent. Compare its local coordinates with its world position and lock it in world space.','Local ↔ world transforms',['Local position','World position','Round-trip error'],'worldPoint = parentMatrix × localPoint\nlocalPoint = inverse(parentMatrix) × worldPoint','A local offset follows the parent’s translation, rotation, and scale. World coordinates describe its position in the scene. Inverting the parent transform converts a world-space point back into local coordinates.','Change parent yaw and scale while holding the local X value fixed. Enable world-position lock, then move the parent: the local coordinates must change to keep the same world point.','Use points for positions and directions for orientation or motion. Translation affects points, not direction vectors. This lab locks position only; the turret’s orientation still inherits its parent.','maths'),
('13-time-steps','Make time explicit.','Simulate 15, 30, 60, or 144 FPS and compare per-frame movement, delta-time movement, and a fixed-step accumulator under hitches.','Frame-rate comparison',['Simulated time','Naive distance','Correct distance'],'wrong: x += speed / 60 per frame\nvariable: x += speed × frameDt\nfixed: accumulate time; step at 120 Hz','The top lane assumes every rendered frame lasts 1/60 second. The others integrate elapsed time. The FPS control simulates an update cadence; it does not change your browser’s actual rendering rate.','Run the two-second trial at 15 FPS, then 144 FPS. Both time-based lanes should finish at speed × 2. Add 200 ms hitches and compare distance with the frame-count method.','Fixed steps make physics behaviour more consistent. Production games also need backlog limits and often interpolate the displayed pose. This small trial processes its full backlog so the accounting is visible.','movement'),
('14-combat-feel','Give an attack a rhythm.','Tune anticipation, active time, recovery, input buffering, knockback, and hit stop. Compare fast and heavy attacks against a training dummy.','Combat timing chamber',['Attack phase','Hits landed','Buffered input'],'startup → active → recovery → ready\npress during recovery → buffer\nhit once per swing, only while active','Startup telegraphs intent; active time can deal a hit; recovery creates commitment. The input buffer queues a future attack, not an immediate cancel. Hit stop freezes combat motion but still accepts input.','Try nimble and heavy presets. Press again just before recovery ends, or use the repeatable combo trial. Remove the input buffer and repeat. Move the dummy outside the reach to see a miss.','Keep collision windows separate from animation appearance. This simplified sector hit test only damages once per swing; health, movement, and defensive mechanics can be added around the same state machine.','feel'),
('15-bezier-paths','Shape the journey.','Drag Bézier control points for a camera rail or projectile path. Compare uniform parameter motion with approximately constant-speed travel.','Curve & arc-length editor',['Curve length','Uniform speed','Arc-length speed'],'B(t) = (1−t)³P₀ + 3(1−t)²tP₁\n       + 3(1−t)t²P₂ + t³P₃\nconstant speed: distance → lookup t','Equal changes in curve parameter t do not generally cover equal distances. A sampled arc-length table maps travelled distance back to t. The orange body uses that table; teal advances directly through t.','Drag the inner handles close to one endpoint. The teal body speeds up and slows down. Pause and scrub, or choose a point and adjust X/Y with the sliders for keyboard access.','Use curves for authored camera paths and projectiles. The arc-length table is a numerical approximation with 400 segments; rebuild it when a control point moves.','maths'),
('16-inverse-kinematics','Let the foot find the ground.','Drag a foot target and solve a two-bone leg. Change limb lengths, bend direction, terrain slope, and body adjustment.','Two-bone IK & foot placement',['Target error','Knee angle','Reach status'],'cos(α) = (L₁² + d² − L₂²) / (2L₁d)\nknee = hip + L₁ × direction(α)\nclamp d to the reachable interval','The solver places the knee using the cosine rule and then connects it to the reachable foot point. Targets outside the limb’s reach are clamped; the orange target stays visible so you can inspect the error.','Drag the foot beyond reach and change the upper/lower lengths. Reverse the knee bend. Switch to terrain placement, change slope, and enable body adjustment to help the leg reach the ground.','Foot placement also needs contact timing, stable bend hints, and joint limits in production. This leg solves in a 2D plane inside the 3D scene; it is not a complete walking controller.','movement'),
('17-audio-feedback','Hear the interaction.','Compare a plain tone with designed pickup, impact, or footstep sounds. Tune pitch variation, layers, envelopes, volume, and feedback delay.','Sound & feedback bench',['Audio status','Designed pitch','Sound delay'],'envelope: attack → exponential decay\npitch = base × 2^(variation / 12)\nfeedback time = event time + delay','A short envelope feels immediate; a longer decay adds weight. Pitch variation reduces repetition. The visual event happens immediately, while the sound follows the chosen delay. Audio is synthesized locally.','Press “Compare A → B” to hear a plain tone followed by the designed version. Toggle tonal and noise layers separately. Add 200 ms delay and notice how the sound disconnects from the visual event.','Keep volume modest and test in context. This is a synthetic sound-design sandbox, not a sample library. Nothing plays until you press a sound button; reset stops scheduled sounds.','feel'),
]
extra_css='''\n.live-graph{width:100%;height:115px;display:block}.screen-zone{position:absolute;border:1px dashed #55d6c288;left:36%;right:36%;top:32%;bottom:32%;pointer-events:none}.catalog-tools{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin:0 0 25px}.catalog-tools input{background:var(--panel);border:1px solid var(--line);border-radius:8px;padding:12px;color:var(--ink);flex:1;min-width:200px}.catalog-tools button[aria-pressed=true]{background:var(--accent);color:#14171c}.catalog-count{color:var(--muted);font:11px Space,monospace}.demo-card[hidden]{display:none}.control input:disabled{opacity:.4}.control label{line-height:1.5}.stat strong{overflow-wrap:anywhere}.legend-strip{position:absolute;top:58px;left:20px;right:20px;font:10px Space;color:#c4cad3;pointer-events:none;line-height:1.8}.control select{min-width:0}@media(max-width:700px){.scene-head{height:auto;min-height:53px}.scene-title{font-size:12px}.legend-strip{font-size:9px}.intro h1{line-height:1.15}.catalog-tools{gap:8px}.catalog-tools button{padding:9px;font-size:12px}}\n'''
for slug,title,desc,scene,metrics,formula,explain,experiment,transfer,group in LABS:
 p=ROOT/slug;p.mkdir(exist_ok=True)
 for file in ['lab.js','lab.css']:
  shutil.copy(ROOT/'01-dot-product'/file,p/file)
  if file == 'lab.js':
   content=(p/file).read_text().replace('Number(el.value).toFixed(step<1?2:0)', 'Number(el.value).toFixed(step<1?Math.ceil(-Math.log10(step)):0)')
   (p/file).write_text(content)
 with (p/'lab.css').open('a') as f:f.write(extra_css)
 shutil.copytree(ROOT/'01-dot-product/assets',p/'assets',dirs_exist_ok=True)
 n=slug[:2];stats=''.join(f'<div class="stat"><label>{v}</label><strong id="stat{i}">—</strong></div>' for i,v in enumerate(metrics))
 lessons=f'<article class="lesson"><h3><span>01</span>The model</h3><div class="formula">{html.escape(formula)}</div><p>{explain}</p></article><article class="lesson"><h3><span>02</span>Try this</h3><p>{experiment}</p></article><article class="lesson"><h3><span>03</span>Take it into a game</h3><p>{transfer}</p></article>'
 (p/'index.html').write_text(f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="{html.escape(desc)}"><title>{title} — CS464 Labs</title><link rel="stylesheet" href="lab.css"></head><body><header class="topbar"><a class="brand" href="../index.html">CS464<b> / LABS</b></a><div class="toplinks"><span class="kicker">MATHS × GAME FEEL</span><a href="../index.html">All labs ↗</a></div></header><main><section class="intro"><div><div class="eyebrow">LAB {n} / {group.upper()}</div><h1>{title}</h1><p>{desc}</p></div><span class="badge">INTERACTIVE SANDBOX</span></section><section class="workspace"><aside class="controls" id="controls"><h2>Tune the experiment</h2></aside><div class="view"><div class="scene-head"><h2 class="scene-title">{scene}</h2><span class="tag">EXPLORE / COMPARE / APPLY</span></div><div class="stage" id="stage"><div class="overlay"><span class="pill" id="status">LOADING SCENE</span></div><div class="stage-help" id="help">Adjust the controls to explore.</div></div><div class="graph-wrap" id="graph-wrap" hidden><canvas id="graph" class="live-graph" role="img" aria-label="Live response graph"></canvas></div><div class="stats">{stats}</div></div></section><section class="lessons">{lessons}</section><footer><span>CS464 / GAME DEVELOPMENT · ITU</span><span>LAB {n} / {scene.upper()}</span><a href="README.md">Notes & source ↗</a></footer></main><noscript><p>Enable JavaScript to run this lab.</p></noscript><script src="assets/three.min.js"></script><script src="lab.js"></script><script src="models.js"></script><script src="extras.js"></script><script src="app.js"></script></body></html>''')
 (p/'README.md').write_text(f'''# Lab {n} — {scene}

{desc}

## Run

Open `index.html` directly. This folder is self-contained, with local Three.js 0.180.0, fonts, scripts, and licenses. No network, build, or install is required. The optional “All labs” link points to the collection and can be ignored when sharing an isolated copy.

A modern browser with WebGL is required. If local HTML is restricted, run `python3 -m http.server 8000` here and open `http://localhost:8000`.

## Experiment

{experiment}

## Maths and assumptions

```
{formula}
```

{explain}

{transfer}

## Source guide

- `app.js`: this experiment’s controls, scene and state.
- `models.js`: pure maths functions, shared as a local copy and covered by the collection’s tests.
- `extras.js`: animation controls, graphs, picking and model helpers.
- `lab.js` / `lab.css`: local course UI and rendering helpers.
- `assets/`: Three.js and course fonts, with their redistribution licenses.

`window.demoState` exposes measurements for teaching and automated checks. Animated demonstrations start paused for users who request reduced motion. Sound only starts after explicit interaction.
''')
# Append illustrated cards while preserving the original five.
svg_shapes=[
'<rect x="78" y="37" width="164" height="95" rx="12" fill="none" stroke="#55d6c2"/><path d="M114 87H205M159 53V121" stroke="#43586c"/><circle cx="183" cy="88" r="15" fill="#ff8a3d"/>',
'<path d="M44 126Q150 9 268 70" fill="none" stroke="#55d6c2" stroke-dasharray="5 5"/><path d="M111 89L133 64L143 99Z" fill="#ff8a3d"/><circle cx="265" cy="71" r="10" fill="#55d6c2"/><circle cx="179" cy="113" r="20" fill="#6c8cff55"/>',
'<path d="M49 44L160 122L270 44" fill="none" stroke="#ff8a3d" stroke-width="3"/><path d="M40 126H280M160 125V27" stroke="#55d6c2" stroke-width="2"/><circle cx="100" cy="80" r="10" fill="#ff8a3d"/>',
'<ellipse cx="160" cy="85" rx="92" ry="32" fill="none" stroke="#ff8a3d"/><ellipse cx="160" cy="85" rx="48" ry="65" fill="none" stroke="#55d6c2"/><ellipse cx="160" cy="85" rx="66" ry="56" fill="none" stroke="#6c8cff" transform="rotate(35 160 85)"/>',
'<path d="M32 120C60 -30 80 169 118 64S161 106 192 78S230 87 286 82" fill="none" stroke="#ff8a3d" stroke-width="3"/><path d="M30 82H289" stroke="#55d6c2" stroke-dasharray="5 5"/>',
'<path d="M38 135Q150 -70 270 92" fill="none" stroke="#ff8a3d" stroke-width="3"/><path d="M38 135L209 92" stroke="#55d6c2" stroke-dasharray="5 5"/><rect x="259" y="84" width="24" height="24" fill="#55d6c2"/>',
'<path d="M65 127V38M65 127H260" stroke="#6c8cff"/><g transform="translate(167 79) rotate(-25)"><rect x="-44" y="-27" width="88" height="54" fill="#55d6c233" stroke="#55d6c2"/><path d="M0 0V-42M0 0H60" stroke="#ff8a3d"/><circle cx="25" cy="-12" r="8" fill="#ff8a3d"/></g>',
'<path d="M40 49H280M40 90H280M40 131H280" stroke="#46566b"/><rect x="242" y="39" width="20" height="20" fill="#ff8a3d"/><rect x="137" y="80" width="20" height="20" fill="#55d6c2"/><rect x="137" y="121" width="20" height="20" fill="#6c8cff"/>',
'<rect x="37" y="96" width="73" height="25" fill="#6c8cff"/><rect x="114" y="96" width="39" height="25" fill="#ff8a3d"/><rect x="157" y="96" width="121" height="25" fill="#55d6c2"/><path d="M122 71L181 26M167 24L185 20L182 39" stroke="#ff8a3d" stroke-width="5"/>',
'<path d="M40 127C210 145 70 8 280 39" fill="none" stroke="#ff8a3d" stroke-width="3"/><path d="M40 127L210 145M70 8L280 39" stroke="#55d6c2" stroke-dasharray="3 4"/><g fill="#55d6c2"><circle cx="40" cy="127" r="7"/><circle cx="210" cy="145" r="7"/><circle cx="70" cy="8" r="7"/><circle cx="280" cy="39" r="7"/></g>',
'<path d="M144 24L203 82L142 132" fill="none" stroke="#55d6c2" stroke-width="9"/><g fill="#ff8a3d"><circle cx="144" cy="24" r="9"/><circle cx="203" cy="82" r="9"/><circle cx="142" cy="132" r="9"/></g><path d="M47 149L270 117" stroke="#6c8cff"/>',
'<path d="M43 83H66L76 52L90 118L103 32L117 132L132 48L145 110L159 65L173 101L189 75L203 92H278" fill="none" stroke="#ff8a3d" stroke-width="3"/>']
cards='<!-- EXPANSION START -->'
for lab,svg in zip(LABS,svg_shapes):
 slug,title,desc,*_=lab;cards+=f'<a class="demo-card" data-group="{lab[-1]}" href="{slug}/index.html"><div class="card-art"><svg viewBox="0 0 320 165" aria-hidden="true">{svg}</svg></div><div class="card-body"><span class="number">EXPERIMENT {slug[:2]} / {lab[-1].upper()}</span><h2>{title}</h2><p>{desc}</p><span class="card-link">Enter the lab ↗</span></div></a>'
cards+='<!-- EXPANSION END -->'
p=ROOT/'index.html';s=p.read_text();s=re.sub(r'<!-- EXPANSION START -->.*?<!-- EXPANSION END -->','',s,flags=re.S)
s=s.replace('<article class="catalog-note">',cards+'<article class="catalog-note">')
s=s.replace('Five hands-on sandboxes','Seventeen hands-on sandboxes').replace('5 LABS ·','17 LABS ·')
for slug,g in [('01-dot-product','maths'),('02-cross-product','maths'),('03-jump-lab','movement'),('04-easing-lab','feel'),('05-game-juice','feel')]:
 s=s.replace(f'<a class="demo-card" href="{slug}/index.html">',f'<a class="demo-card" data-group="{g}" href="{slug}/index.html">')
if 'id="catalog-search"' not in s:
 bar='<div class="catalog-tools"><input id="catalog-search" type="search" placeholder="Find a concept, technique, or lab…" aria-label="Search labs"><button data-filter="all" aria-pressed="true">All labs</button><button data-filter="maths" aria-pressed="false">Maths</button><button data-filter="movement" aria-pressed="false">Movement</button><button data-filter="feel" aria-pressed="false">Game feel</button><span class="catalog-count" id="catalog-count" aria-live="polite">17 labs</span></div>'
 s=s.replace('<section class="catalog"',bar+'<section class="catalog"');s=s.replace('</body>','<script src="catalog.js"></script></body>')
p.write_text(s)
p=ROOT/'lab.css';s=p.read_text();
if '.catalog-tools{' not in s:p.write_text(s+extra_css)
